[package]
name = "PrimeVectors"
version = "0.1.0"
authors = ["xCuzImVinni"]
edition = "2024"
[dependencies]
csv = "1.3.1"
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.32.1"
rand = "0.8"
rayon = "1.10.0"
sysinfo = "0.35.2"
